### ISSUE TITLE
Parameter to change compression level (window size)

### ISSUE THREAD

**Issue by fredonred** [opencomputeproject/Project-Zipline#5]
Is the RTL parameterized to facilitate the support for smaller search window sizes?

Also, the symbol_queue in the RTL (cr_huf_comp_sq.v) defaults to a depth of 20,480. Is it safe to use a smaller queue? What are the factors I should consider when changing the size of this queue?

**Comment by michaelgmcintyre** [comment]
Hi fredonred,

Is the RTL parameterized to facilitate the support for smaller search window sizes?

_The size of the window can be passed to the current RTL via TLVs.  Unfortunately, there is no explicit RTL parameter to shrink the design if an implementation wished to support only a smaller frame.  However, the design could be shrunk.  It is possible that tying off the search window size to a smaller value would save many gates if the synthesizer realizes those gates are no longer necessary.  Otherwise the design would require some rework._

Also, the symbol_queue in the RTL (cr_huf_comp_sq.v) defaults to a depth of 20,480. Is it safe to use a smaller queue? What are the factors I should consider when changing the size of this queue?

_The RTL uses this value to check for compressibility and to emit the first Huffman block.  Our analysis showed that limiting this value could result in smaller initial Huffman blocks which reduced the compression ratio.  For our application it made sense to set this parameter to a large value._

Best regards
